# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


plugin 'cocoapods-gitee-repo', :sources => [
  'demo-cocoapods-remote'
]

target 'helloworld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  #pod 'AFNetworking' , '>=4.0.1'
  pod 'SwiftyJSON', '5.0.0'
end
