FROM docker:dind

# 支持多架构构建
ARG TARGETARCH

ENV MAVEN_VERSION=3.8.9 \
    NODE_VERSION=24.11.0 \
    GO_VERSION=1.22.3 \
    HELM_VERSION=3.14.4 \
    GRADLE_VERSION=7.2 \
    Nerdctl_VERSION=1.7.5 \
    DOCKER_TLS_CERTDIR=""

RUN apk add --no-cache \
    bash curl vim openjdk17 nodejs npm \
    python3 py3-pip jq zip tar xz unzip 

# Nerdctl
RUN if [ "$TARGETARCH" = "amd64" ]; then ARCH_TAG="amd64"; \
    elif [ "$TARGETARCH" = "arm64" ]; then ARCH_TAG="arm64"; \
    else echo "❌ Unsupported architecture: $TARGETARCH" && exit 1; fi && \
    curl -LO https://github.com/containerd/nerdctl/releases/download/v${Nerdctl_VERSION}/nerdctl-${Nerdctl_VERSION}-linux-${ARCH_TAG}.tar.gz \
    | tar -C /usr/local/bin -xvzf nerdctl-${Nerdctl_VERSION}-linux-${ARCH_TAG}.tar.gz 

# Maven
RUN curl -fsSL "https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz" \
    | tar -xz -C /opt && \
    ln -sf /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/bin/mvn

# Go
RUN if [ "$TARGETARCH" = "amd64" ]; then ARCH_TAG="amd64"; \
    elif [ "$TARGETARCH" = "arm64" ]; then ARCH_TAG="arm64"; \
    else echo "❌ Unsupported architecture: $TARGETARCH" && exit 1; fi && \
    curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-${ARCH_TAG}.tar.gz" \
    | tar -C /usr/local -xzf - && ln -sf /usr/local/go/bin/go /usr/bin/go

# Helm
RUN if [ "$TARGETARCH" = "amd64" ]; then ARCH_TAG="amd64"; \
    elif [ "$TARGETARCH" = "arm64" ]; then ARCH_TAG="arm64"; \
    else echo "❌ Unsupported architecture: $TARGETARCH" && exit 1; fi && \
    curl -fsSL "https://get.helm.sh/helm-v${HELM_VERSION}-linux-${ARCH_TAG}.tar.gz" \
    | tar -xz && mv linux-${ARCH_TAG}/helm /usr/bin/helm && rm -rf linux-${ARCH_TAG}

# Gradle
RUN curl -fsSL "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" -o gradle.zip && \
    unzip gradle.zip -d /opt && rm gradle.zip && \
    ln -sf /opt/gradle-${GRADLE_VERSION}/bin/gradle /usr/bin/gradle

# Python
RUN ln -sf python3 /usr/bin/python && \
    pip install --break-system-packages twine build

# Demo files
COPY demo/ /root/demo
WORKDIR /root

#设置时区
ENV TZ=Asia/Shanghai
RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT ["dockerd-entrypoint.sh"]
