FROM cruizba/ubuntu-dind

# 多架构参数（amd64 / arm64）
ARG TARGETARCH

ENV MAVEN_VERSION=3.8.9 \
    GRADLE_VERSION=7.2 \
    NODE_VERSION=18.19.0 \
    GO_VERSION=1.22.3 \
    HELM_VERSION=3.14.4 \
    DOCKER_TLS_CERTDIR="" \
    Nerdctl_VERSION=1.7.5 \
    TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive \
    MAMBA_ROOT_PREFIX=/opt/conda \
    PATH=/opt/conda/bin:/root/.cargo/bin:/root/demo/nuget:/root/package/${TARGETARCH}/dotnet-sdk-10.0.102/:/root/package/${TARGETARCH}/ohpm/bin/:$PATH

# 集中架构判断（仅此一处）
RUN if [ "$TARGETARCH" = "amd64" ]; then \
        ARCH_TAG="amd64"; \
        CONDA_ARCH="x86_64"; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        ARCH_TAG="arm64"; \
        CONDA_ARCH="aarch64"; \
    else \
        echo "❌ Unsupported architecture: $TARGETARCH" && exit 1; \
    fi && \
    echo "ARCH_TAG=$ARCH_TAG" >> /etc/environment && \
    echo "CONDA_ARCH=$CONDA_ARCH" >> /etc/environment

SHELL ["/bin/bash", "-c"]

#设置时区
RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 基础工具和语言环境（不区分架构，但包含了构建工具和一些常用语言环境，且清理了缓存和不必要的文件以减小镜像体积）
RUN apt-get update && apt-get install -y --no-install-recommends \
    vim jq unzip bzip2 cmake openssl ca-certificates \
    # php php-cli php-phar php-mbstring php-xml php-curl php-zip ruby ruby-dev \
    openjdk-17-jdk git-lfs nodejs npm  && \
    # git-lfs 
    git lfs install && \
    rm -rf /var/lib/apt/lists/*

# Maven（不区分架构）
RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    | tar -xz -C /opt && ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/bin/mvn 

# Gradle（不区分架构）
RUN curl -fsSL "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" -o gradle.zip && \
    unzip gradle.zip -d /opt && rm gradle.zip && \
    ln -sf /opt/gradle-${GRADLE_VERSION}/bin/gradle /usr/bin/gradle

# Go
RUN source /etc/environment && \
    curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-${ARCH_TAG}.tar.gz" \
    | tar -C /usr/local -xzf - && ln -sf /usr/local/go/bin/go /usr/bin/go 

# Helm
RUN source /etc/environment && \
    curl -fsSL "https://get.helm.sh/helm-v${HELM_VERSION}-linux-${ARCH_TAG}.tar.gz" \
    | tar -xz && mv linux-${ARCH_TAG}/helm /usr/bin/helm && rm -rf linux-${ARCH_TAG}

# Python来自Conda(base) (需要twine、build）
# huggingface-hub（不区分架构）
# conan(依赖cmake、openssl、build-base等系统包，且需要生成配置文件)
RUN source /etc/environment && \
    curl -fsSL "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-${CONDA_ARCH}.sh" -o miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh && \
    /opt/conda/bin/conda init bash && \
    # 激活 base 环境
    . /opt/conda/etc/profile.d/conda.sh && conda activate base && \
    # 安装python构建工具、huggingface-hub、conan，并清理缓存 
    pip install --no-cache-dir twine build && \
    # pip install --no-cache-dir twine build huggingface-hub==0.26.3 conan==2.23.0 && \
    # conan profile detect --force && \
    conda clean -afy && \
    rm -rf /opt/conda/pkgs

# # Nerdctl
# RUN source /etc/environment && \
#     curl -fL -o nerdctl.tgz \
#       https://github.com/containerd/nerdctl/releases/download/v${Nerdctl_VERSION}/nerdctl-${Nerdctl_VERSION}-linux-${ARCH_TAG}.tar.gz && \
#     tar -xzf nerdctl.tgz -C /usr/local/bin && \
#     rm nerdctl.tgz

# # Cargo
# RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal && \
#     /root/.cargo/bin/rustup component remove rust-docs || true && \
#     rm -rf /root/.cargo/registry && \
#     rm -rf /root/.cargo/git

# # Composer
# RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
#     php composer-setup.php && \
#     php -r "unlink('composer-setup.php');" && \
#     mv composer.phar /usr/local/bin/composer

# # Nuget+Ohpm
# COPY package/${TARGETARCH}/ /root/package/${TARGETARCH}/

# # CocoaPods（不区分架构，但需要安装ruby和相关依赖）
# RUN gem install cocoapods --no-document && \
#     gem install cocoapods-gitee-repo --no-document && \
#     gem cleanup && \
#     rm -rf /usr/lib/ruby/gems/*/cache/*.gem && \
#     rm -rf /root/.gem

# 项目文件
COPY demo/ /root/demo

WORKDIR /root