export default {
  Main: {
    xiaYiBu: "Next step",
    zhiXingWanCheng: "Execute completion",
    peiZhiWanChengDa: "It takes about 5 minutes to complete the configuration, please wait patiently",
    zhengZaiPeiZhiZhu: "Configure host information",
    qingZaiNinDeZhu: "Please perform the following script as root in your host",
    qingYiGuanLiYuan: "Please perform the following script as an administrator in the terminal",
    bingFaXianZhi: "Concurrent limit",
    qingShuRuZhuJi: "Please enter the number",
    gengDuoPeiZhi: "More configuration",
    sSHDuanKou: "SSH port number",
    qingShuRuDuanKou: "Please enter the port number, the default is {val1}",
    zhuJiMiMaChang: "The length of the host password should be 3-100 characters",
    zhuJiYongHuMing: "The length of the host user name should be in 3-32 characters",
    qingShuRuZhuJi2: "Please enter the host user name",
    renZhengFangShi: "Verification method",
    qingShuRuIP: "Please enter the IP address of IPv4 format",
    zhuJiLeiXing: "Host type",
    ceShiLianJie: "Test link",
    shangYiBu: "Previous",
    aGENT: "The agent agent has been online, and the host information is detected as follows:",
    mACDiZhi: "MAC address",
    iPXinXi: "IP information",
    cPUGE: "CPU: {val1} Memory: {val2}",
    qingShuRuZhuJi3: "Please enter the host description",
    zhuJiMiaoShu: "Host description",
    qingZhiShaoXuanZe: "Please choose at least one service unit",
    fuWuDanYuanZhu: "Host unit",
    shouQuanXiangMu: "Authorized project",
    muBiaoFenZuShou: "Target group authorization project",
    qingXuanZeShangJi: "Please choose a superior group",
    muBiaoFenZu: "Target group",
    wanCheng: "Finish",
    sHouZiDongFan: "Return to the list page automatically after 5s",
    ceShiTongGuo: "Test",
    iTEML: "{val1} host",
    anZhuangShiYuDao: "I encounter problems during installation",
    tianJiaZhuJiDao: "Add host to group",
    huoQuZhiXingA: "Get the execution of the Agent script",
    tianXieZhuJiXin: "Fill in the host information",
    quXiaoXuanZe: "cancel selection",
    quanXuanDangQianFen: "Selected current grouping",
    taiZhuJi: "Host",
    yiXuanZhong: "selected",
    shengJiPeiZhi: "Upgrade configuration",
    tianJiaZhuJi: "Add a host",
    qingZhiShaoXuanZe2: "Please choose at least one host",
    yiDongDao: "Move to",
    quanBuZhuangTai: "All states",
    qingKong: "Empty"
  },
  SideBar: {
    xinJianFenZu: "New grouping",
    zhuJiZiYuanZu: "Host resource group"
  }
}

