export default {
  TimeSelector: {
    jinTian: '近7天',
    jinXiaoShi: '近24小时',
    shiShi: '实时',
  },
  AddGroupModal: {
    suoYouZhuJi: '所有主机',
    queDingYaoShanChu: '确定要删除主机组：{val1} 吗？',
    shanChuQueRen: '删除确认',
    qingXuanZeShouQuan: '请选择授权项目',
    qingXuanZeSSuoShu: '请选择所属项目',
    qingShuRuFenZu: '请输入分组描述',
    fenZuMiaoShu: '分组描述',
    qingShuRuFenZu2: '请输入分组名',
    fenZuMing: '分组名',
    weiYiBiaoZhi: '唯一标识',
    shangJiFenZu: '上级分组',
    aGENT: '{val1}分组',
  },
  AgentGroupTree: {
    xiang: '项',
    xiangMuJi: '项目级',
    qi: '企',
    qiYeJi: '企业级',
    zhuJiFenZuBu: '主机分组不能超过5个层级',
    lABEL: '{val1}分组',
    dangQianJinZhiChi: '当前仅支持同级拖拽',
  },
  DeleteAgentModal: {
    beiShanChuZhuJi: '被删除主机历史数据无法恢复，确认操作?',
    beiShanChuZhuJi2:
      '被删除主机正在运行及新接收的任务均会运行失败且历史数据无法恢复，确认操作?',
  },
  ExecuteScript: {
    muBiaoFuWuQi: '目标服务器',
    qingShuRuChaoShi: '请输入超时时长',
    chaoShiShiChangMiao: '超时时长（秒）',
    qingShuRuJiaoBen: '请输入脚本内容',
    jiaoBenNeiRong: '脚本内容',
    xuanZeJiaoBen: '选择脚本',
    jiaoBenMingCheng: '脚本名称',
    qingXuanZeJiaoBen: '请选择脚本',
    qingXuanZeJiaoBen2: '请选择脚本来源',
    jiaoBenLaiYuan: '脚本来源',
    buZhouMingCheng: '步骤名称',
    zhiXing: '执行',
    zhiXingXiangQing: '执行详情',
  },
  ExecutiveLog: {
    zanWuRiZhi: '暂无日志',
    zhiXingJieGuo: '执行结果',
  },
  FileDistribution: {
    fenFa: '分发',
    buZhouMingChengXian: '步骤名称限60个字符',
    qingShuRuBuZhou: '请输入步骤名称',
    qingWuTianXieYi: '请勿填写一台主机上的相同路径',
    dangQianYouBenDi: '当前有本地文件未上传完成，请等待上传成功后保存',
    qingZhiShaoXuanZe: '请至少选择一个源文件',
    qingTianXieFenFa: '请填写分发路径',
    muBiaoLuJing: '目标路径',
    chuanShuMuBiao: '传输目标',
    qingXuanZeFuWu: '请选择服务器',
    qingShuRuWenJian: '请输入文件路径',
    qingXuanZeWenJian: '请选择文件来源',
    wenJianLaiYuan: '文件来源',
    qiYongXiaZaiXian: '启用下载限速',
    qiYongShangChuanXian: '启用上传限速',
    chaoShiShiChangMiao: '超时时长(秒)',
    chuanShuMoShi: '传输模式',
    yanJinPanDuanMu: '严谨判断目标路径是否存在，若不存在将直接终止任务。',
    yanJinMoShiZhi: '严谨模式指：',
    buLunMuBiaoLu:
      '不论目标路径是否存在，都将强制按照用户填写的目标路径进行传输（路径不存在会自动创建）。',
    qiangZhiMoShiZhi: '强制模式指：',
  },
  LogItem: {
    fuZhiShiBai: '复制失败！',
    wuXiaoFuZhiNei: '无效复制（内容为空）！',
    fuZhiChengGong: '复制成功！',
  },
  ShutDownOrRebootAgentModal: {
    shouQi: '收起',
    ninYiXuanZe: '您已选择 ',
    houZhiLingJiangWu: '后指令将无法终止',
    queDingAnNiu: '确定按钮',
    miaoHouFaSongDian: '秒后发送,点击',
    zhiLingJiangZai: '指令将在 ',
    shiDuanNeiZhengZai: '时段内正在运行及新接收的任务均会运行失败，是否进行',
    suoXuanZhuJi: '所选主机',
    aGENT: '{val1}主机',
    quXiaoCaoZuo: '取消操作',
    queDingCaoZuo: '确定操作',
  },
  ShutdownOrRebootConfig: {
    kuanShuShiJianZui: '宽恕时间最小值为{val1}',
    qingSheZhiKuanShu: '请设置宽恕时间',
    kuanShuShiJian: '宽恕时间',
    kuanShuShiJianTip: '宽恕时间为主机延迟关闭/重启时间，如设置为60秒，则在60秒后执行关闭/重启操作',
  },
  TargetServer: {
    qingXuanZeLI: '请选择Linux类型服务器',
    qingXuanZeWin: '请选择Windows类型服务器',
    wINDO: 'Windows无法运行Linux Bash\n',
    linuxINDO: 'Linux无法运行Bat\n',
  },
  UpdateAgent: {
    aGENT: 'Agent 版本升级',
  },
};
