export default {
  constant: {
    queRenZhuJiGui: '确认主机规格信息',
    yuZhuJiJianLi: '与主机建立连接',
    anZhuangAGE: '安装Agent服务',
    guanBi: '关闭',
    yiDong: '移动',
    bianJi: '编辑',
    chaKan: '查看',
    xinJian: '新建',
    shouDongAnZhuangZhong: '手动安装重连主机',
    tongGuoSSH: '通过SSH重连主机',
    shouDongAnZhuangTian: '手动安装添加主机',
    tongGuoSSH2: '通过SSH添加主机',
    chuangJianShiJian: '创建时间',
    aGENT: 'Agent 版本',
    mACDiZhi: 'MAC 地址',
    cunChuG: '存储(G)',
    neiCunG: '内存(G)',
    cPUHe: 'CPU(核)',
    suoShuZiYuanZu: '所属资源组',
    zhuJiID: '主机ID',
  },
};
