export default {
  constantWithReactFC: {
    shiBai: '失败',
    chengGong: '成功',
    jinXingZhong: '进行中',
    dengDaiZhong: '等待中',
  },
  index: {
    yanJinMoShi: '严谨模式',
    qiangZhiMoShi: '强制模式',
    jiaoBenYinRu: '脚本引入',
    shouDongLuRu: '手动录入',
    aGENT:
      'Agent升级时正在执行的任务任务将直接失败，不会重新放回任务等待队列，请确保不会影响任务后进行升级。',
    dengDaiShengJiWan: '等待升级完成执行任务',
    dingShiShengJi: '定时升级',
    ziDongShengJi: '自动升级',
    weiFenPeiZhuJi: '未分配主机组',
    anZhuangZhong: '安装中',
    shanChu: '删除',
    liXian: '离线',
    zaiXian: '在线',
    caoZuoChengGong: '操作成功',
    renGongQueRen: '人工确认',
    wenJianFenFa: '文件分发',
    jiaoBenZhiXing: '脚本执行',
    rongQiYunXing: '容器运行',
    zhuJiYunXing: '主机运行',
    zhanNeiXin: '站内信',
    weiXin: '微信',
    duanXin: '短信',
    youJian: '邮件',
  },
};
