export default {
  ExecDetailDrawer: {
    zhiXingChaoShi: '执行超时',
    chaKanRiZhi: '查看日志',
    quanBuZhuJiZhong: '全部主机重试',
    haoShi: '耗时：',
    kaiShiShiJian: '开始时间：',
    jieShuShiJian: '结束时间：',
    zongHaoShi: '总耗时：',
    zhuangTai: '状态：',
    faQiShiJian: '发起时间：',
    faQiRen: '发起人：',
    zuoYeEXE: '作业{val1}的执行详情',
  },
  constant: {
    buTongGuo: '不通过',
    queRenTongGuo: '确认通过',
    huLueCuoWu: '忽略错误',
    zhiXingZanTing: '执行暂停',
    zhiXingChengGong: '执行成功',
    zhiXingShiBai: '执行失败',
    zhiXingZhong: '执行中',
    daiZhiXing: '待执行',
  },
  index: {
    zhiXingMingLing: '执行命令',
    jiaoBen: '脚本',
    chaKanXiangQing: '查看详情',
    zhiXingZhuangTai: '执行状态',
    haoShiS: '耗时(s)',
    zhiXingKaiShiShi: '执行开始时间',
    zuoYeID: '作业ID',
    zhiXingID: '执行ID',
  },
};
