export default {
  Main: {
    xiaYiBu: '下一步',
    zhiXingWanCheng: '执行完成',
    peiZhiWanChengDa: '配置完成大概需要5分钟，请耐心等待',
    zhengZaiPeiZhiZhu: '正在配置主机信息',
    qingZaiNinDeZhu: '请在您的主机中以root身份执行以下脚本',
    qingYiGuanLiYuan: '请以管理员身份在终端执行以下脚本',
    bingFaXianZhi: '并发限制',
    qingShuRuZhuJi: '请输入主机并发数目',
    gengDuoPeiZhi: '更多配置',
    sSHDuanKou: 'ssh端口号',
    qingShuRuDuanKou: '请输入端口号，默认为{val1}',
    zhuJiMiMaChang: '主机密码长度应在3-100字符',
    zhuJiYongHuMing: '主机用户名长度应在3-32字符',
    qingShuRuZhuJi2: '请输入主机用户名',
    renZhengFangShi: '认证方式',
    qingShuRuIP: '请输入IPV4格式的IP地址',
    zhuJiLeiXing: '主机类型',
    ceShiLianJie: '测试链接',
    shangYiBu: '上一步',
    aGENT: 'Agent代理已上线，检测到主机信息如下：',
    mACDiZhi: 'MAC地址',
    iPXinXi: 'IP信息',
    cPUGE: 'CPU: {val1} 内存：{val2}',
    qingShuRuZhuJi3: '请输入主机描述',
    zhuJiMiaoShu: '主机描述',
    qingZhiShaoXuanZe: '请至少选择一个服务单元',
    fuWuDanYuanZhu: '服务单元',
    shouQuanXiangMu: '授权项目',
    muBiaoFenZuShou: '目标分组授权项目',
    qingXuanZeShangJi: '请选择上级分组',
    muBiaoFenZu: '目标分组',
    wanCheng: '完成',
    sHouZiDongFan: '5s后自动返回列表页',
    ceShiTongGuo: '测试通过',
    iTEML: '{val1}主机',
    anZhuangShiYuDao: '安装时遇到问题',
    tianJiaZhuJiDao: '添加主机到分组',
    huoQuZhiXingA: '获取执行Agent脚本',
    tianXieZhuJiXin: '填写主机信息',
    quXiaoXuanZe: '取消选择',
    quanXuanDangQianFen: '全选当前分组',
    taiZhuJi: '台主机',
    yiXuanZhong: '已选中',
    shengJiPeiZhi: '升级配置',
    tianJiaZhuJi: '添加主机',
    qingZhiShaoXuanZe2: '请至少选择一个主机',
    yiDongDao: '移动到',
    quanBuZhuangTai: '全部状态',
    qingKong: '清空',
  },
  SideBar: {
    xinJianFenZu: '新建分组',
    zhuJiZiYuanZu: '主机资源组',
  },
};
