/* eslint-disable */
// @ts-nocheck
// 临时文件  dev.gitee.work

export const agents = [
    {
        'labelId': 31,
        'jarDownload': 'wget -O agent.jar https://dev.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s https://dev.gitee.work/sa_server -t 8cc88d93-a7db-44c5-b245-68963568f913 >> run.log 2>&1 &',
        'startShell': 'curl -s https://dev.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u https://dev.gitee.work/sa_server -t 8cc88d93-a7db-44c5-b245-68963568f913',
        'origin': 'SELF',
        'serverArg': 'https://dev.gitee.work',
        'jarUrl': 'https://dev.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'note': '',
        'status': 'OFFLINE',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '8cc88d93-a7db-44c5-b245-68963568f913',
        'createTime': '2022-03-25 18:06:54',
        'name': '192.168.80.19',
    }, {
        'labelId': 31,
        'jarDownload': 'wget -O agent.jar https://dev.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s https://dev.gitee.work/sa_server -t eafb746f-9d27-406d-831d-a11d4428f348 >> run.log 2>&1 &',
        'startShell': 'curl -s https://dev.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u https://dev.gitee.work/sa_server -t eafb746f-9d27-406d-831d-a11d4428f348',
        'origin': 'SELF',
        'serverArg': 'https://dev.gitee.work',
        'jarUrl': 'https://dev.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': null,
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'note': '',
        'status': 'ONLINE',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': 'eafb746f-9d27-406d-831d-a11d4428f348',
        'createTime': '2022-03-22 10:16:25',
        'name': 'agent-sun',
    }, {
        'labelId': 31,
        'jarDownload': 'wget -O agent.jar https://dev.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s https://dev.gitee.work/sa_server -t b68911b7-0d65-4c0c-97ce-cb4fccc23b64 >> run.log 2>&1 &',
        'startShell': 'curl -s https://dev.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u https://dev.gitee.work/sa_server -t b68911b7-0d65-4c0c-97ce-cb4fccc23b64',
        'origin': 'SELF',
        'serverArg': 'https://dev.gitee.work',
        'jarUrl': 'https://dev.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'note': '',
        'status': 'ONLINE',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': 'b68911b7-0d65-4c0c-97ce-cb4fccc23b64',
        'createTime': '2022-03-22 10:15:59',
        'name': 'agent-mars',
    }, {
        'labelId': 31,
        'jarDownload': 'wget -O agent.jar https://dev.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s https://dev.gitee.work/sa_server -t 72eca435-687a-41be-91d4-af34fe3046c3 >> run.log 2>&1 &',
        'startShell': 'curl -s https://dev.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u https://dev.gitee.work/sa_server -t 72eca435-687a-41be-91d4-af34fe3046c3',
        'origin': 'SELF',
        'serverArg': 'https://dev.gitee.work',
        'jarUrl': 'https://dev.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'note': '',
        'status': 'ONLINE',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '72eca435-687a-41be-91d4-af34fe3046c3',
        'createTime': '2022-03-22 10:15:47',
        'name': 'agent-moon',
    }, {
        'labelId': 31,
        'jarDownload': 'wget -O agent.jar https://dev.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s https://dev.gitee.work/sa_server -t dfbd155f-46fb-407d-a265-7862a49d60d4 >> run.log 2>&1 &',
        'startShell': 'curl -s https://dev.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u https://dev.gitee.work/sa_server -t dfbd155f-46fb-407d-a265-7862a49d60d4',
        'origin': 'SELF',
        'serverArg': 'https://dev.gitee.work',
        'jarUrl': 'https://dev.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.2.9',
        'latestVersion': '1.2.9',
        'cpuUsedRate': '39%',
        'memoryUsedRate': '42%',
        'note': '',
        'status': 'ONLINE',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': 'dfbd155f-46fb-407d-a265-7862a49d60d4',
        'createTime': '2022-03-21 14:59:53',
        'name': 'agent-saturn',
    }, {
        'labelId': 31,
        'jarDownload': 'wget -O agent.jar https://dev.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s https://dev.gitee.work/sa_server -t b00a23f1-01fb-499d-8b16-9aba020ac161 >> run.log 2>&1 &',
        'startShell': 'curl -s https://dev.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u https://dev.gitee.work/sa_server -t b00a23f1-01fb-499d-8b16-9aba020ac161',
        'origin': 'SELF',
        'serverArg': 'https://dev.gitee.work',
        'jarUrl': 'https://dev.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.3.0',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'note': '',
        'status': 'OFFLINE',
        'hiGroup': null,
        'executorCount': 5,
        'sendEmail': null,
        'type': 2,
        'uuid': 'b00a23f1-01fb-499d-8b16-9aba020ac161',
        'createTime': '2022-03-17 09:35:53',
        'name': '192.168.137.104',
    }, {
        'labelId': 31,
        'jarDownload': 'wget -O agent.jar https://dev.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s https://dev.gitee.work/sa_server -t a950d5f1-a6ad-42da-ba41-d4921b393f8e >> run.log 2>&1 &',
        'startShell': 'curl -s https://dev.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u https://dev.gitee.work/sa_server -t a950d5f1-a6ad-42da-ba41-d4921b393f8e',
        'origin': 'SELF',
        'serverArg': 'https://dev.gitee.work',
        'jarUrl': 'https://dev.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.3.0',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'note': '',
        'status': 'OFFLINE',
        'hiGroup': null,
        'executorCount': 5,
        'sendEmail': null,
        'type': 2,
        'uuid': 'a950d5f1-a6ad-42da-ba41-d4921b393f8e',
        'createTime': '2022-03-17 09:35:13',
        'name': '192.168.137.101',
    }, {
        'labelId': 31,
        'jarDownload': 'wget -O agent.jar https://dev.gitee.work/sa_server/agent/v1/download',
        'runCommand': 'nohup java -jar -Dfile.encoding=UTF-8 agent.jar -s https://dev.gitee.work/sa_server -t 15715fc9-7f35-4189-9fad-7b5b7496dcad >> run.log 2>&1 &',
        'startShell': 'curl -s https://dev.gitee.work/sa_server/agent/v1/download/start | bash -s -- -u https://dev.gitee.work/sa_server -t 15715fc9-7f35-4189-9fad-7b5b7496dcad',
        'origin': 'SELF',
        'serverArg': 'https://dev.gitee.work',
        'jarUrl': 'https://dev.gitee.work/sa_server/agent/v1/download',
        'runningTaskCount': 0,
        'waitingTaskCount': 0,
        'groupName': null,
        'currentVersion': '1.3.0',
        'latestVersion': '1.2.9',
        'cpuUsedRate': null,
        'memoryUsedRate': null,
        'note': '',
        'status': 'OFFLINE',
        'hiGroup': null,
        'executorCount': 10,
        'sendEmail': null,
        'type': 2,
        'uuid': '15715fc9-7f35-4189-9fad-7b5b7496dcad',
        'createTime': '2022-03-16 18:01:10',
        'name': '192.168.137.100',
    }];

export const labels = [
    {
        'id': 33,
        'name': 'noah_test_20220317',
        'displayName': 'noah-test-20220317',
        'createTime': '2022-03-17 11:10:32',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'labelAgentRels': null,
        'type': 2,
        'agentEntities': null,
        'companyUuid': null,
        'groupName': 'osc',
        'origin': 'SELF',
        'authorizeProjects': ['*'],
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 1,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 31,
        'name': 'zc_test',
        'displayName': 'zc-test',
        'createTime': '2022-03-16 17:58:33',
        'deleteStatus': false,
        'description': '',
        'purpose': 1,
        'labelAgentRels': null,
        'type': 2,
        'agentEntities': null,
        'companyUuid': null,
        'groupName': 'cloudideTest',
        'origin': 'SELF',
        'authorizeProjects': [],
        'groupType': 2,
        'labelType': 1,
        'registerAgentNum': 8,
        'activeAgentNum': 1,
        'oldDisplayName': null,
    }, {
        'id': 29,
        'name': 'zgx_test',
        'displayName': 'zgx-test',
        'createTime': '2022-03-15 15:28:48',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'labelAgentRels': null,
        'type': 2,
        'agentEntities': null,
        'companyUuid': null,
        'groupName': 'osc',
        'origin': 'SELF',
        'authorizeProjects': ['*'],
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 2,
        'activeAgentNum': 1,
        'oldDisplayName': null,
    }, {
        'id': 5,
        'name': 'cq000',
        'displayName': 'cq000',
        'createTime': '2022-02-25 10:09:14',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'labelAgentRels': null,
        'type': 2,
        'agentEntities': null,
        'companyUuid': null,
        'groupName': 'osc',
        'origin': 'SELF',
        'authorizeProjects': ['*'],
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    }, {
        'id': 1,
        'name': 'noah_test',
        'displayName': 'noah-test',
        'createTime': '2022-02-23 10:24:02',
        'deleteStatus': false,
        'description': '',
        'purpose': 3,
        'labelAgentRels': null,
        'type': 2,
        'agentEntities': null,
        'companyUuid': null,
        'groupName': 'osc',
        'origin': 'SELF',
        'authorizeProjects': ['*'],
        'groupType': 1,
        'labelType': 3,
        'registerAgentNum': 0,
        'activeAgentNum': 0,
        'oldDisplayName': null,
    },
];






