/* eslint-disable */
// @ts-nocheck
// 脚本列表临时文件
export const TEMP_SCRIPTS = [{
    'id': 701,
    'name': 'Demo-0310',
    'version': 2051,
    'category': 2,
    'os': 'Linux',
    'language': 'Linux Bash',
    'languageDependencies': {'centos': '7'},
    'description': '1111',
    'scope': 'global',
    'params': null,
    'script': 'sleep 5\necho 1111',
    'recommendedDockerImageUrl': 'registry.baidubce.com/gitee-prod/centos:centos8',
    'createTime': '2022-03-10 18:20:43',
    'createUser': 'guwenxiang1998',
    'modifiedTime': '2022-03-10 18:20:43',
    'modifiedUser': 'guwenxiang1998',
}, {
    'id': 699,
    'name': 'Proxima-打包机器',
    'version': 2049,
    'category': 5,
    'os': 'Linux',
    'language': 'Linux Bash',
    'languageDependencies': {'centos': '7'},
    'description': '',
    'scope': 'global',
    'params': null,
    'script': 'echo ${CORE_DOCKER_IMAGE_URL} > images.txt\necho ${APP_DOCKER_IMAGE_URL} >> images.txt\necho ${CAMUNDA_DOCKER_IMAGE_URL} >> images.txt\necho ${VM_DOCKER_IMAGE_URL} >> images.txt\n\necho "版本号:${REALSE_VERSION}"\necho ${REALSE_VERSION} > version\n\nfileName=$(date +\'%Y-%m-%d_%H%M%S\').zip\necho 文件名称:$fileName\necho $fileName > fileName\n\n## 复制 version \nsshpass -p \'OSCcc@2022\' ssh root@192.168.80.87 "rm -rf /data/version"\nsshpass -p \'OSCcc@2022\' scp ./version root@192.168.80.87:/data\n\n## 复制 fileName\nsshpass -p \'OSCcc@2022\' ssh root@192.168.80.87 "rm -rf /data/fileName"\nsshpass -p \'OSCcc@2022\' scp ./fileName root@192.168.80.87:/data\n\n## 复制  images.txt\nsshpass -p \'OSCcc@2022\' ssh root@192.168.80.87 "rm -rf /data/images.txt"\nsshpass -p \'OSCcc@2022\' scp ./images.txt root@192.168.80.87:/data\n\n\n## 清除历史文件\nsshpass -p \'OSCcc@2022\' ssh root@192.168.80.87 "rm -rf /data/*.tgz"\nsshpass -p \'OSCcc@2022\' ssh root@192.168.80.87 "rm -rf /data/*.zip"\n\n## 执行\nsshpass -p \'OSCcc@2022\' ssh root@192.168.80.87 "cd /data; sh package.sh"\n\necho "下载升级包请执行命令:curl -u admin:password -O http://192.168.81.17:31090/artifactory/Proxima/$fileName"\n\n\n\n',
    'recommendedDockerImageUrl': 'registry.baidubce.com/gitee-prod/alpine-sshpass:0.0.3',
    'createTime': '2022-03-08 18:18:13',
    'createUser': 'wuchengguo',
    'modifiedTime': '2022-03-09 16:01:39',
    'modifiedUser': 'wuchengguo',
}, {
    'id': 697,
    'name': 'JMeter压测',
    'version': 2009,
    'category': 4,
    'os': 'Linux',
    'language': 'Groovy',
    'languageDependencies': {'Java JDK': '9', 'Groovy': '2.5'},
    'description': '',
    'scope': 'global',
    'params': [{
        'defaultValue': 'demo.jmx',
        'name': 'JmeterJmxPath',
        'options': [],
        'description': 'JMX文件路径',
        'type': 'TEXT',
        'required': true,
    }, {
        'defaultValue': 'dev-jmeter.gitee.work',
        'name': 'DomainHost',
        'options': [],
        'description': '平台域名或IP端口',
        'type': 'TEXT',
        'required': true,
    }, {'name': 'OtherCmdParamtr', 'options': [], 'description': '其他命令参数', 'type': 'TEXT', 'required': false}],
    'script': 'set -e\npwd=`pwd`\ndate=`date +%s`\njmeterzip="jmeter.zip"\nresult="${pwd}/resultjmt"\nresult_jtl="${result}/result${date}.jtl"\nresult_log="${result}/result${date}.log"\njtl_url=""\nlog_url=""\nmkdir -p ${result}\n\necho "--------- jmeter脚本下载: IPIPE_JMETER_ZIP ---------"\ncurl -o $jmeterzip http://osc.gitee.work:9000/job-center/staging-area/2022-03/1646128985/artifact_IPIPE_JMETER_ZIP.zip\nunzip -o jmeter.zip > /dev/null 2>&1\nls\necho "--------- jmeter脚本下载完成 ---------"\necho "JMX文件路径：${JmeterJmxPath}"\necho "平台域名或IP端口：${DomainHost}"\necho "其他参数：${OtherCmdParamtr}"\necho "--------- Jmeter版本 ---------"\njmeter -v\necho "--------- 开始运行 ---------"\necho "jmeter -n -t ${pwd}/${JmeterJmxPath} -l ${result_jtl} -j ${result_log} -Jhost=${DomainHost} ${OtherCmdParamtr}"\njmeter -n -t ${JmeterJmxPath} -l ${result_jtl} -j ${result_log} -Jhost=${DomainHost} ${OtherCmdParamtr}\n\necho "--------- 开始上传JTL\\LOG ---------"\nif [ -f "${result_jtl}" ];then\ncurl -u admin:password -X PUT "http://192.168.81.17:31090/artifactory/DEV/result${date}.jtl" -T ${result_jtl}\njtl_url="http://192.168.81.17:31090/artifactory/DEV/result${date}.jtl"\nfi\n\nif [ -f "${result_log}" ];then\ncurl -u admin:password -X PUT "http://192.168.81.17:31090/artifactory/DEV/result${date}.log" -T ${result_log}\nlog_url="http://192.168.81.17:31090/artifactory/DEV/result${date}.log"\nfi\n\necho "****************** 结果 ******************"\necho "JTL：${jtl_url}"\necho "LOG：${log_url}"\necho "****************************************"\n\necho "--------- 完成 ---------"\n\n',
    'recommendedDockerImageUrl': 'registry.baidubce.com/gitee-prod/jmeter:5.1.1',
    'createTime': '2022-03-01 17:47:00',
    'createUser': 'lifei',
    'modifiedTime': '2022-03-01 18:51:07',
    'modifiedUser': 'lifei',
}, {
    'id': 695,
    'name': 'mdk-deploy',
    'version': 1943,
    'category': 5,
    'os': 'Linux',
    'language': 'Linux Bash',
    'languageDependencies': {'centos': '7'},
    'description': '',
    'scope': 'global',
    'params': [{
        'defaultValue': '${xxxx}',
        'name': 'aryifactName',
        'options': [],
        'description': '制品名词',
        'type': 'TEXT',
        'required': false,
    }],
    'script': '\necho ${aryifactName}\ngit clone  http://username:password@xxxxx\n\nwget http://192.168.81.17:31090/artifactory/list/DEV/checkout.sh\nbash checkout.sh\n\n\ngit clone ssh://git@osc.gitee.work:5503/enterprise__pipe-sjal/gradle-demo.git\n\nwgte ${]\nunzip\n\n\n\necho hello\n\nunzip  \n\necho AGILE_WORKSPACE=v1.0.0',
    'recommendedDockerImageUrl': 'registry.baidubce.com/gitee-poc/centos:7',
    'createTime': '2022-02-23 19:13:25',
    'createUser': 'dekeMa',
    'modifiedTime': '2022-02-23 19:13:25',
    'modifiedUser': 'dekeMa',
}, {
    'id': 693,
    'name': 'Java_应用部署_测试',
    'version': 1941,
    'category': 3,
    'os': 'Linux',
    'language': 'Linux Bash',
    'languageDependencies': {'centos': '7'},
    'description': '非共用',
    'scope': 'global',
    'params': [{
        'name': 'APP_PUB_PATH',
        'options': [],
        'description': '部署文件路径',
        'type': 'TEXT',
        'required': true,
    }, {
        'defaultValue': '8080',
        'name': 'APP_PORT',
        'options': [],
        'description': '部署端口',
        'type': 'TEXT',
        'required': true,
    }],
    // eslint-disable-next-line max-len
    'script': '# 需要做路径安全监测, 避免删除操作系统关键核心文件\n# 逻辑：\n# 1. 用户输入应用名称、版本、发布地址、端口、环境等信息\n# 2. 支持用户设置是否停止并清除已有应用, 或停止并直接覆盖已有应用\n# 3. 对应用启停做脚本支持与检查\n\nrm -rf /root/lhc/apps/${APP_PUB_PATH}\nmkdir -p /root/lhc/apps/${APP_PUB_PATH}\n\ncd /root/lhc/apps/${APP}\nwget "${AGILE_PRODUCT_PATH}"\n\ntar -xvf *.tar\ncd target\n\nmv *.jar ${APP}.jar\n\njava -jar ${APP}.jar --server.port=${APP_PORT} &',
    'recommendedDockerImageUrl': 'registry.baidubce.com/gitee-poccentos:7',
    'createTime': '2022-02-22 17:53:00',
    'createUser': 'liuhongchao',
    'modifiedTime': '2022-02-22 17:53:27',
    'modifiedUser': 'liuhongchao',
}, {
    'id': 689,
    'name': 'hha-test',
    'version': 1923,
    'category': 5,
    'os': 'Linux',
    'language': 'Linux Bash',
    'languageDependencies': {'centos': '7'},
    'description': '',
    'scope': 'global',
    'params': null,
    'script': 'echo',
    'recommendedDockerImageUrl': 'centos',
    'createTime': '2022-01-17 15:41:04',
    'createUser': 'pipe',
    'modifiedTime': '2022-01-17 15:41:04',
    'modifiedUser': 'pipe',
}, {
    'id': 600,
    'name': 'Git依赖打包',
    'version': 1937,
    'category': 2,
    'os': 'Linux',
    'language': 'Linux Bash',
    'languageDependencies': {'centos': '7'},
    'description': '',
    'scope': 'global',
    'params': [{
        'name': 'CLONE_SHELL',
        'options': [],
        'description': '克隆命令',
        'type': 'TEXT',
        'required': true,
    }, {
        'name': 'ARTIFACT_PATH',
        'options': [],
        'description': '制品路径',
        'type': 'TEXT',
        'required': true,
    }, {
        'name': 'ARTIFACT_NAME',
        'options': [],
        'description': '制品名称',
        'type': 'TEXT',
        'required': true,
    }, {'name': 'PACKAGE_PATH', 'options': [], 'description': '打包路径', 'type': 'TEXT', 'required': true}],
    'script': '${CLONE_SHELL} \n\ntar -czvf ${ARTIFACT_NAME}.tar.gz ${PACKAGE_PATH} \n\nPRODUCT_PATH=http://192.168.81.17:31090/artifactory/DEV/${ARTIFACT_NAME}.tar.gz\n\ncurl -u admin:password -X PUT "${PRODUCT_PATH}" -T ${ARTIFACT_NAME}.tar.gz\n\nout -k IPIPE_CODE_PRODUCT -val ${PRODUCT_PATH}\n\n',
    'recommendedDockerImageUrl': 'registry.baidubce.com/gitee-poccentos:7',
    'createTime': '2021-08-13 06:02:14',
    'createUser': 'lifei',
    'modifiedTime': '2022-02-16 17:42:11',
    'modifiedUser': 'lifei',
}, {
    'id': 585,
    'name': 'proxima-环境部署',
    'version': 1929,
    'category': 3,
    'os': 'Linux',
    'language': 'Linux Bash',
    'languageDependencies': {'centos': '7'},
    'description': 'registry.baidubce.com/gitee-prod/alpine-sshpass:0.0.3',
    'scope': 'global',
    'params': [{
        'defaultValue': 'gitee-proxima-app',
        'name': 'APP_NAME',
        'options': [],
        'description': '',
        'type': 'TEXT',
        'required': false,
    }, {
        'name': 'PROXIMA_APP_IMAGE',
        'options': [],
        'description': '',
        'type': 'TEXT',
        'required': false,
    }, {
        'name': 'PROXIMA_CORE_IMAGE',
        'options': [],
        'description': '',
        'type': 'TEXT',
        'required': false,
    }, {
        'name': 'PROXIMA_VM_IMAGE',
        'options': [],
        'description': '',
        'type': 'TEXT',
        'required': false,
    }, {'name': 'PROXIMA_CAMUNDA_IMAGE', 'options': [], 'description': '', 'type': 'TEXT', 'required': false}],
    // eslint-disable-next-line max-len
    'script': 'set -e\nstr=``\nif [ -n "${PROXIMA_APP_IMAGE}" ]; then str="${str} -a ${PROXIMA_APP_IMAGE}"; fi\nif [ -n "${PROXIMA_CORE_IMAGE}" ]; then str="${str} -c ${PROXIMA_CORE_IMAGE}"; fi\nif [ -n "${PROXIMA_VM_IMAGE}" ]; then str="${str} -v ${PROXIMA_VM_IMAGE}"; fi\nif [ -n "${PROXIMA_CAMUNDA_IMAGE}" ]; then str="${str} -b ${PROXIMA_CAMUNDA_IMAGE}"; fi\n\necho ${str}\n\nif [[ $(expr match "$DOCKER_TAG" \'test\') != 0 ]]; then\n  echo "部署功能测试环境"\n  sshpass -p \'OSCcc@2021\' ssh root@192.168.81.61 "cd /home/proxima-compose && sh ./ci.sh $str"\n  exec_result=$?\n  if [[ "$exec_result" = "0" ]]; then\n    echo "Success"\n    exit 0\n  else\n    echo "failure"\n    exit 1\n  fi\nelif [[ $(expr match "$DOCKER_TAG" \'dev\') != 0 ]]; then\n  echo "部署开发联调环境"\n  sshpass -p \'OSCcc@2022\' ssh root@192.168.80.87 "cd /root/proxima-compose && sh ./ci.sh $str"\n  exec_result=$?\n  if [[ "$exec_result" = "0" ]]; then\n    echo "Success"\n    exit 0\n  else\n    echo "failure"\n    exit 1\n  fi\nelif [[ $(expr match "$DOCKER_TAG" \'feature\') != 0 ]]; then\n  echo "部署分支测试环境"\n  sshpass -p \'OSCcc@2021\' ssh root@192.168.80.100 \'cd /root/proxima-compose && sh ./ci.sh $str\'\n  exec_result=$?\n  if [[ "$exec_result" = "0" ]]; then\n    echo "Success"\n    exit 0\n  else\n    echo "failure"\n    exit 1\n  fi\nelse\n  echo "跳过部署"\nfi',
    'recommendedDockerImageUrl': 'registry.baidubce.com/gitee-poc/centos:7',
    'createTime': '2021-07-05 06:18:44',
    'createUser': 'wusilun',
    'modifiedTime': '2022-01-19 11:19:05',
    'modifiedUser': 'yezhiming',
}, {
    'id': 535,
    'name': 'Chart发布至Nexus',
    'version': 2015,
    'category': 5,
    'os': 'Linux',
    'language': 'Linux Bash',
    'languageDependencies': {'centos': '7'},
    'description': '',
    'scope': 'global',
    'params': [{
        'name': 'ChartDir',
        'options': [],
        'description': '',
        'type': 'TEXT',
        'required': true,
    }, {
        'defaultValue': 'gitee-prod',
        'name': 'repoName',
        'options': [],
        'description': '',
        'type': 'TEXT',
        'required': true,
    }],
    'script': 'date=`date +%s`\nmkdir -p /chart\ncd /chart\ncurl -o chart.zip ${IPIPE_CHART_ZIP}\nunzip chart.zip -d chart\ncd chart\nls\ncd ${ChartDir}\nresult=`/helm/3.4.0/helm package ./ |grep "tgz" | awk -F\'[:] \' \'{print $2}\'`\nif [ ! -n $result ]; then  \n  echo "打包失败"\n  exit 1 \nfi \n\ncurl -u admin:password -X PUT "http://192.168.81.17:31090/artifactory/DEV/${date}${result}" -T ${result}\n\necho "================================"\necho "chart remote web URL ：http://192.168.81.17:31090/artifactory/DEV/${date}${result}"\necho "================================"\n\nout -k IPIPE_CHART_PATH -val "http://192.168.81.17:31090/artifactory/DEV/${date}${result}"',
    'recommendedDockerImageUrl': 'registry.baidubce.com/gitee-poccentos:7',
    'createTime': '2021-02-23 03:35:02',
    'createUser': 'lifei',
    'modifiedTime': '2022-03-03 11:28:13',
    'modifiedUser': 'lifei',
}, {
    'id': 193,
    'name': '生成参数-容器运行',
    'version': 2019,
    'category': 5,
    'os': 'Linux',
    'language': 'Linux Bash',
    'languageDependencies': {'centos': '7'},
    'description': '可创建下游可使用的参数，可将冲突的参数改变为其他的Key去承载',
    'scope': 'global',
    'params': [{
        'defaultValue': 'IPIPE_',
        'name': 'PARAM_KEY',
        'options': [],
        'description': '参数的Key',
        'type': 'TEXT',
        'required': true,
    }, {
        'defaultValue': '参数值,可${}引用上游参数',
        'name': 'PARAM_VALUE',
        'options': [],
        'description': '参数的值，可使用${}',
        'type': 'TEXT',
        'required': true,
    }],
    'script': 'echo "目标参数Key：${PARAM_KEY}"\necho "Value：${PARAM_VALUE}"\n\nout -k ${PARAM_KEY} -val ${PARAM_VALUE}',
    'recommendedDockerImageUrl': 'registry.baidubce.com/gitee-poc/alpine:0.0.1',
    'createTime': '2020-12-24 07:23:49',
    'createUser': 'lifei',
    'modifiedTime': '2022-03-07 19:33:11',
    'modifiedUser': 'lifei',
}];
