/* eslint-disable */
// @ts-nocheck
// 用户列表临时文件 基于 test环境 test.gitee.work
export const users = [
    {
        'userId': '47',
        'displayName': 'zhangchao_v',
        'companyUuid': 'osc',
        'role': [{
            'id': null,
            'createUser': null,
            'createTime': null,
            'updateUser': null,
            'updateTime': null,
            'name': '企业管理员',
            'code': 'COMPANY_ADMIN',
            'editable': null,
            'companyUuid': null,
            'describes': null,
        }],
        'applyStatus': 'SUCCESS',
        'latestTime': 1648453135000,
        'latestTimeStr': '2022-03-28 15:38:55',
        'enterpriseCard': '张超',
        'email': 'bingzhijinshu@163.com',
        'realmType': 'NONE',
        'editable': true,
        'gitEmail': 'bingzhijinshu@163.com',
    },
    {
        'userId': '175',
        'displayName': 'zhaoyunxiao',
        'companyUuid': 'osc',
        'role': [{
            'id': null,
            'createUser': null,
            'createTime': null,
            'updateUser': null,
            'updateTime': null,
            'name': '企业成员',
            'code': 'COMPANY_MEMBER',
            'editable': null,
            'companyUuid': null,
            'describes': null,
        }],
        'applyStatus': 'SUCCESS',
        'enterpriseCard': 'zhaoyunxiao',
        'email': 'zhaoyunxiao@oschina.cn',
        'realmType': 'NONE',
        'editable': true,
        'gitEmail': 'zhaoyunxiao@oschina.cn',
    },
]

export const currentUsers = {
    'code': 0,
    'message': '查询成功',
    'payload': {
        'userId': '175',
        'enterpriseCard': '赵云枭',
        'imageUrl': null,
        'displayName': 'zhaoyunxiao',
        'bosKey': null,
        'workWeiXin': null,
        'realmType': 'NONE',
        'userType': 'NONE',
        'email': 'zhaoyunxiao@oschina.cn',
        'companyIdentity': 'COMPANY_ADMIN',
        'rtxAccount': null,
        'roles': null,
        'hasChangedPass': true,
        'gitEmail': 'zhaoyunxiao@oschina.cn',
    },
}
